spring.application.name=banking
# MySQL Connection Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/bankdb?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root

# Hibernate / JPA Configuration
# 'update' automatically validates and updates schema without dropping existing records
spring.jpa.hibernate.ddl-auto=update

# Show generated SQL statements in the STS/Eclipse Console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

